### ISSUE TITLE
2.0.0 cannot find packageurl-js

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-webpack-plugin#56]
When upgrading from 1.0.1 to 2.0.0, I receive the following error:

```
 ERROR  Error loading vue.config.js:
 ERROR  Error: Cannot find module 'packageurl-js'
 Require stack:
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/src/webpack-plugin/bomGenerator.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/src/bom/index.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/src/webpack-plugin/index.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/index.js
- /Users/steve/Development/Dependency-Track/frontend/vue.config.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@vue/cli-service/lib/Service.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'packageurl-js'
Require stack:
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/src/webpack-plugin/bomGenerator.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/src/bom/index.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/src/webpack-plugin/index.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/index.js
- /Users/steve/Development/Dependency-Track/frontend/vue.config.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@vue/cli-service/lib/Service.js
- /Users/steve/Development/Dependency-Track/frontend/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/src/webpack-plugin/bomGenerator.js:21:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/steve/Development/Dependency-Track/frontend/node_modules/@cyclonedx/webpack-plugin/src/bom/index.js:20:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @dependencytrack/frontend@4.4.0 build: `npm run prebuild && vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
```

Reverting back to 1.0.1 solves the issue.

**Comment by jkowalleck** [comment]
@stevespringett
do you have a reproducible setup for this issue?  how did you do the upgrade?

**Comment by stevespringett** [comment]
I'm going to close. Must have been an issue with GH Actions at the time, because now it seems to be working fine.

**Comment by jkowalleck** [comment]
i am glad to hear that.
